### PR TITLE
Add required deps for building locally

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
`gettext` is installed by default and not removable in Pop!_OS. Other distributions could be different, so listing it is fine, but in Pop!_OS, `msgfmt` is also required to build but is not installed by default. Is this list supposed to be exhaustive?

**Comment by 13r0ck** [comment]
I tried building locally again on 21.04 & 21.10, building from source via `make && make install` fails until installing `gettext`.

On master_impish building also fails unless installing `sassc`. But this PR is not for impish

**Comment by 13r0ck** [comment]
Impish now has better docs. This is no longer necessary

**Comment by 13r0ck** [comment]
Impish now has better docs. This is no longer necessary

**Pull request closed without merging**
