### PR TITLE
Update Website button URL to our fork

### LINKED ISSUE #79: Extensions app links to Dash to Dock extension webpage.
# Summary

`Website` button under Cosmic Dock extension in the GNOME Extensions app links to Dash to Dock web page.

## Recreate Issue

1. Open "Extensions" app.
2. Click on drop-down arrow ">" next to Cosmic Dock.
3. Click `Website` Button.
4. Browser opens to this site: https://micheleg.github.io/dash-to-dock/ 

## Expected Behavior

Step 4 should link to: https://github.com/pop-os/cosmic-dock

### PR DESCRIPTION
**Pull request by leviport**
Closes https://github.com/pop-os/cosmic-dock/issues/79

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
This doesn't seem to be working, the button is still opening the old link:
Screenshot from 2021-11-08 08-48-48

**Review by jacobgkau — CHANGES_REQUESTED** [review]
Looks like it also needs to be updated in `metadata.json`, that might be what the button uses: https://github.com/pop-os/cosmic-dock/blob/fa4d6917c11659c19a502df7f044b46b03dd58e0/metadata.json

**Comment by leviport** [comment]
Aha, I'll make that change

**Review by jacobgkau — APPROVED** [review]
Button now opens the correct page.

**Pull request merged**
