### PR TITLE
Don't show dGPU launch item if backed by NVIDIA

### PR DESCRIPTION
**Pull request by crawfxrd**
pop-os/gnome-shell#89

### CODE REVIEW

**Comment by jacobgkau** [comment]
I had to rebase on master_jammy because the package was requiring gnome-shell < 41 (it looked like it had been based on master_impish before.)

**Comment by jacobgkau** [comment]
The package installs now, but the context menu doesn't work for dock icons. I get an empty menu in the top-left of the screen instead:

Screenshot from 2022-03-15 14-17-21

This happens in any graphics mode. I get this journalctl output when it happens:

```
Mar 15 14:20:06 pop-os gnome-shell[2474]: Failed to import DBusMenu, quicklists are not avaialble: Error: Requiring Dbusmenu, version none: Typelib file for namespace 'Dbusmenu' (any version) not found
Mar 15 14:20:06 pop-os gnome-shell[2474]: JS ERROR: TypeError: Shell.util_get_gl_vendor is not a function
                                          _rebuildMenu@/usr/share/gnome-shell/extensions/cosmic-dock@system76.com/appIcons.js:1041:32
                                          popup@/usr/share/gnome-shell/extensions/cosmic-dock@system76.com/appIcons.js:989:14
                                          popupMenu@/usr/share/gnome-shell/extensions/cosmic-dock@system76.com/appIcons.js:421:20
                                          vfunc_button_press_event@resource:///org/gnome/shell/ui/appDisplay.js:3202:18
```

**Comment by crawfxrd** [comment]
Is `gnome-shell` updated as well? It requires the changes from the linked PR.

**Comment by jacobgkau** [comment]
Ah, that explains it. No, it's not updated yet, because gnome-shell master_jammy build failed after the PR was merged:

```
[1mgnome-shell: 8130d99400120f310f4a3f1153a8a573ee3e01c8 (master_jammy): jammy (22.04): amd64: binary building[0m
[1mgnome-shell: 8130d99400120f310f4a3f1153a8a573ee3e01c8 (master_jammy): jammy (22.04): binary-amd64 github status pending[0m
[1mgnome-shell: 8130d99400120f310f4a3f1153a8a573ee3e01c8 (master_jammy): jammy (22.04): arm64: binary building[0m
[1mgnome-shell: 8130d99400120f310f4a3f1153a8a573ee3e01c8 (master_jammy): jammy (22.04): binary-arm64 github status pending[0m
E: Package build dependencies not satisfied; skipping
[1mgnome-shell: 8130d99400120f310f4a3f1153a8a573ee3e01c8 (master_jammy): jammy (22.04): amd64: binary failed: exit code: 3[0m
[1mgnome-shell: 8130d99400120f310f4a3f1153a8a573ee3e01c8 (master_jammy): jammy (22.04): binary-amd64 github status failure[0m
E: Package build dependencies not satisfied; skipping
[1mgnome-shell: 8130d99400120f310f4a3f1153a8a573ee3e01c8 (master_jammy): jammy (22.04): arm64: binary failed: exit code: 3[0m
[1mgnome-shell: 8130d99400120f310f4a3f1153a8a573ee3e01c8 (master_jammy): jammy (22.04): binary-arm64 github status failure[0m
```

Trying to build locally, it looks like `apt build-dep gnome-shell` wants mutter 42 but only 41 is available.

**Review by jackpot51 — DISMISSED** [review]

**Review by jacobgkau — APPROVED** [review]
Alright, this is working now, and it hides the `Launch using Discrete Graphics Card` (or `Launch using Integrated Graphics Card`) option in NVIDIA mode. Still shows up in Hybrid mode. Does not show up in Integrated mode or Compute mode. Steam launches successfully in all graphics modes.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
