### PR TITLE
Fix cosmic-workspaces conflict & always center app icons in dock

### LINKED ISSUE #129: [22.04] Cosmic-Dock extension breaks workspaces after various state changes.
Moving dock location, changing resolution, and potentially other actions leads to the workspace picker and the workspace view breaking: 

https://user-images.githubusercontent.com/98765732/160918375-03a3937f-e9b6-4427-97f2-cc2ff537e22a.mp4

With the cosmic-dock extension disabled, this does not present, nor does it present in 21.10 or earlier. Restarting gnome fixes the issue, but any further update to the dock breaks workspaces and its view again. It also seems to persist across reboots most of the time.

### LINKED ISSUE #130: [22.04] Cosmic does does not retain icon centring
While I doubt these are the only manipulations which can break dock centring as I noticed it at least once before without these procedures, however if I: 

1) toggle dock extend-to-edge off
2) change dock location
and 
3) toggle dock extend-to-edge back on
the dock is no longer correctly centred. 

Example:

https://user-images.githubusercontent.com/98765732/161116695-9fe94358-ff52-408e-8866-ec507aab445b.mp4

This same behaviour presents if: 
1) extend-to-edge is toggled off
2) the resolution is changed 
and
3) extend-to-edge is toggled back on. 

I also would note that this fail state producible through the same techniques as #129

### PR DESCRIPTION
**Pull request by 13r0ck**
Requires pop-os/cosmic-workspaces#56
Fixes #130

Closes #129

### CODE REVIEW

**Comment by 13r0ck** [comment]
This closes #129, but it breaks the workspaces view if `cosmic-workspaces` is disabled. Rather than just deleting the functions I need to only inject the functions if `cosmic-workspaces` is enabled

**Review by jackpot51 — DISMISSED** [review]
Looks similar to something I had to do before

**Review by n3m0-22 — COMMENTED** [review]
Cosmic does does not retain icon centring #130 is still an issue

https://user-images.githubusercontent.com/11048214/161865719-c7ccafd8-1813-4c01-8483-94f466c57aea.mp4


https://user-images.githubusercontent.com/11048214/161865737-a822b055-0970-4171-aab5-5aec78ae10c3.mp4

Steps to reproduce:
1. Start with dock on the bottom
2. Make sure extend dock is ticked
3. Move the dock to the right edge
4. Untick extend dock
5. Move dock to the bottom edge
6. Tick extend dock

Now the icons should be shifted to the left. This will also happen by doing the inverse and starting from either side moving to the bottom and then back to the side, but now the icons are shifted to the top. It seems to happen no matter the settings on options, visibility, and only on primary as well as all displays. It also affects the icon alignment on the secondary display.

As for the other issues listed here
https://github.com/pop-os/cosmic-dock/issues/129

and here
https://github.com/pop-os/cosmic-workspaces/pull/56

I see no evidence of them.

I have tested with three external monitors at several resolutions bigger, smaller, and the same as the laptop display.

```
apt policy gnome-shell-extension-cosmic-workspaces
gnome-shell-extension-cosmic-workspaces:
  Installed: 0.1.0~1649198366~22.04~b80291b
  Candidate: 0.1.0~1649198366~22.04~b80291b
  Version table:
 *** 0.1.0~1649198366~22.04~b80291b 1002
       1002 http://apt.pop-os.org/staging/workspaces-more-jammy-fixes jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/workspaces-more-jammy-fixes jammy/main i386 Packages
        100 /var/lib/dpkg/status
     0.1.0~1648501522~22.04~c60edc2 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
user@pop-os:~ $ apt policy gnome-shell-extension-cosmic-dock

```

```
apt policy gnome-shell-extension-cosmic-dock
gnome-shell-extension-cosmic-dock:
  Installed: 72~ubuntu2pop0~1649127336~22.04~892a232
  Candidate: 72~ubuntu2pop0~1649127336~22.04~892a232
  Version table:
 *** 72~ubuntu2pop0~1649127336~22.04~892a232 1002
       1002 http://apt.pop-os.org/staging/workspaces-more-jammy-fixes jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/workspaces-more-jammy-fixes jammy/main i386 Packages
        100 /var/lib/dpkg/status
     72~ubuntu2pop0~1649110273~22.04~39ffde8 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages

```

**Comment by 13r0ck** [comment]
@n3m0-22 you arn't on the right commit. You need to be on [5e0e665](https://github.com/pop-os/cosmic-dock/pull/132/commits/5e0e665fb832683317afb554992937d355d484fa) your apt policy is 892a232

**Review by n3m0-22 — APPROVED** [review]
This solves the issues of icon alignment when moving the dock.

**Comment by n3m0-22** [comment]
@13r0ck you are correct. My apologies, I missed that update while testing it. I have corrected the mistake. Thanks

**Comment by 13r0ck** [comment]
@n3m0-22 lol all good. I did the same thing when I started in QA :smile:

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
